<?php
/**
 * FileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CoverService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DDB Cover Service Upload
 *
 * <p>The service is provided by <a href=\"https://www.danskernesdigitalebibliotek.dk/\">Danskernes Digitale Bibliotek</a></p> <p><a href=\"https://www.gnu.org/licenses/agpl-3.0.en.html\">GNU Affero General Public License</a></p>
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CoverService;

/**
 * FileTest Class Doc Comment
 *
 * @category    Class
 * @description File
 * @package     CoverService
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "File"
     */
    public function testFile()
    {
    }

    /**
     * Test attribute "mime_type"
     */
    public function testPropertyMimeType()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
    }

    /**
     * Test attribute "extension"
     */
    public function testPropertyExtension()
    {
    }

    /**
     * Test attribute "basename"
     */
    public function testPropertyBasename()
    {
    }

    /**
     * Test attribute "pathname"
     */
    public function testPropertyPathname()
    {
    }

    /**
     * Test attribute "perms"
     */
    public function testPropertyPerms()
    {
    }

    /**
     * Test attribute "inode"
     */
    public function testPropertyInode()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "a_time"
     */
    public function testPropertyATime()
    {
    }

    /**
     * Test attribute "m_time"
     */
    public function testPropertyMTime()
    {
    }

    /**
     * Test attribute "c_time"
     */
    public function testPropertyCTime()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "writable"
     */
    public function testPropertyWritable()
    {
    }

    /**
     * Test attribute "readable"
     */
    public function testPropertyReadable()
    {
    }

    /**
     * Test attribute "executable"
     */
    public function testPropertyExecutable()
    {
    }

    /**
     * Test attribute "file"
     */
    public function testPropertyFile()
    {
    }

    /**
     * Test attribute "dir"
     */
    public function testPropertyDir()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "link_target"
     */
    public function testPropertyLinkTarget()
    {
    }

    /**
     * Test attribute "real_path"
     */
    public function testPropertyRealPath()
    {
    }

    /**
     * Test attribute "file_info"
     */
    public function testPropertyFileInfo()
    {
    }

    /**
     * Test attribute "path_info"
     */
    public function testPropertyPathInfo()
    {
    }

    /**
     * Test attribute "file_class"
     */
    public function testPropertyFileClass()
    {
    }

    /**
     * Test attribute "info_class"
     */
    public function testPropertyInfoClass()
    {
    }
}
