<?php
/**
 * MaterialApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CoverService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DDB Cover Service Upload
 *
 * <p>The service is provided by <a href=\"https://www.danskernesdigitalebibliotek.dk/\">Danskernes Digitale Bibliotek</a></p> <p><a href=\"https://www.gnu.org/licenses/agpl-3.0.en.html\">GNU Affero General Public License</a></p>
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CoverService;

use CoverService\Configuration;
use CoverService\ApiException;
use CoverService\ObjectSerializer;

/**
 * MaterialApiTest Class Doc Comment
 *
 * @category Class
 * @package  CoverService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MaterialApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteMaterialItem
     *
     * Removes the Material resource..
     *
     */
    public function testDeleteMaterialItem()
    {
    }

    /**
     * Test case for getMaterialCollection
     *
     * Retrieves the collection of Material resources..
     *
     */
    public function testGetMaterialCollection()
    {
    }

    /**
     * Test case for getMaterialItem
     *
     * Retrieves a Material resource..
     *
     */
    public function testGetMaterialItem()
    {
    }

    /**
     * Test case for postMaterialCollection
     *
     * Creates a Material resource..
     *
     */
    public function testPostMaterialCollection()
    {
    }
}
